repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-json
    -   id: check-merge-conflict
    -   id: detect-private-key

-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
        language_version: python3.8

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: ["--profile", "black"]

-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-docstrings]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
    -   id: mypy
        additional_dependencies: 
            - PyQt5-stubs
            - types-mutagen
            - types-requests>=2.31.0
            - types-setuptools
            - sphinx~=5.3.0
            - sphinx-rtd-theme~=1.1.1

-   repo: https://github.com/PyCQA/pylint
    rev: v2.17.0
    hooks:
    -   id: pylint
        args: ["--disable=C0111"]  # Disable missing-docstring warning

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
    -   id: pyupgrade
        args: [--py38-plus]

-   repo: https://github.com/commitizen-tools/commitizen
    rev: v2.42.1
    hooks:
    -   id: commitizen
        stages: [commit-msg] 