name: Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            qt-deps: python3-qt5 qt5-qmake qttools5-dev-tools
          - os: macos-latest
            qt-deps: qt@5
          - os: windows-latest
            qt-deps: ""
        
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"
        
    - name: Install Qt dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y ${{ matrix.qt-deps }}
        
    - name: Install Qt dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install ${{ matrix.qt-deps }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
        
    - name: Build with PyInstaller
      run: python build.py
        
    - name: Generate SHA256 checksums
      run: |
        cd dist
        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          Get-FileHash -Algorithm SHA256 * | ForEach-Object { $_.Hash + " " + $_.Path } > SHA256SUMS
        else
          shasum -a 256 * > SHA256SUMS
        fi
      shell: pwsh
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: jellyfin-music-organizer-${{ matrix.os }}
        path: |
          dist/*
          dist/SHA256SUMS
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/*
          dist/SHA256SUMS
        body: |
          Release ${{ github.ref_name }}
          
          SHA256 Checksums:
          ```
          ${{ runner.os }}:
          $(cat dist/SHA256SUMS)
          ```
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
