name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"
        
    - name: Install formatting tools
      run: |
        python -m pip install --upgrade pip
        pip install black isort autoflake
        
    - name: Format with black and isort
      run: |
        black .
        isort .
        
    - name: Apply manual fixes
      run: |
        # Fix error_handler.py
        sed -i 's/from typing import.*ParamSpec.*/from typing import Any, Callable, Dict, List, TypeVar\nfrom typing_extensions import ParamSpec  # Single import/' jellyfin_music_organizer/utils/error_handler.py
        
        # Fix organize_thread.py
        sed -i 's/metadata_dict = self.metadata_handler.extract_metadata(file_path)/return self.metadata_handler.extract_metadata(file_path)/' jellyfin_music_organizer/core/organize_thread.py
        
    - name: Configure Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        
    - name: Commit changes
      id: commit
      continue-on-error: true
      run: |
        git add .
        git diff --quiet && git diff --staged --quiet || (git commit -m "style: format code and fix linting issues" && git push)
        echo "changes_made=$?" >> $GITHUB_OUTPUT

  lint:
    needs: format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0
        
    - name: Wait for format changes
      run: |
        sleep 10
        git pull origin ${{ github.head_ref || 'main' }} --rebase
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black flake8 mypy isort
        pip install -r requirements.txt
        
    - name: Check formatting with black
      run: black --check .
      
    - name: Lint with flake8
      run: |
        flake8 . \
          --count \
          --max-line-length=120 \
          --statistics \
          --exclude=.git,__pycache__,build,dist,*.egg-info \
          --extend-ignore=E203,W503 \
          --per-file-ignores="__init__.py:F401 build.py:E501"

    - name: Run additional checks
      run: |
        # Check for duplicate imports
        python -c "
        import ast, sys
        for file in sys.argv[1:]:
            try:
                with open(file) as f:
                    tree = ast.parse(f.read())
                imports = {}
                for node in ast.walk(tree):
                    if isinstance(node, (ast.Import, ast.ImportFrom)):
                        for name in node.names:
                            if name.name in imports:
                                print(f'{file}: Duplicate import of {name.name}')
                            imports[name.name] = True
            except Exception as e:
                print(f'Error processing {file}: {e}')
        " $(find . -name "*.py")

    - name: Type check with mypy
      run: |
        mypy jellyfin_music_organizer \
          --ignore-missing-imports \
          --disallow-untyped-defs \
          --check-untyped-defs \
          --warn-redundant-casts \
          --warn-unused-ignores \
          --warn-return-any \
          --no-warn-unused-ignores

    - name: Check import sorting
      run: isort --check-only --diff .
