name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"
        
    - name: Install formatting tools
      run: |
        python -m pip install --upgrade pip
        pip install black isort
        
    - name: Format with black and isort
      run: |
        black .
        isort .
        
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "style: auto-format with black and isort"
        branch: ${{ github.head_ref }}

  lint:
    needs: format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0
        
    - name: Fetch latest changes
      run: |
        git fetch origin
        git checkout ${{ github.head_ref }}
        git pull origin ${{ github.head_ref }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install linting tools
        pip install black flake8 mypy isort
        # Install project dependencies (PyQt5 includes its own type hints)
        pip install -r requirements.txt
        
    - name: Check formatting with black
      run: black --check .
      
    - name: Lint with flake8
      run: |
        flake8 . \
          --count \
          --max-line-length=100 \
          --statistics \
          --exclude=.git,__pycache__,build,dist,*.egg-info
      
    - name: Type check with mypy
      run: |
        mypy jellyfin_music_organizer \
          --ignore-missing-imports \
          --disallow-untyped-defs \
          --check-untyped-defs \
          --warn-redundant-casts \
          --warn-unused-ignores \
          --warn-return-any \
          --no-warn-unused-ignores

    - name: Check import sorting
      run: isort --check-only --diff .
