name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    needs: lint  # Add dependency on lint job
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # PyQt5 5.15.10 and other dependencies work best with Python 3.8-3.10
        python-version: ["3.8", "3.9", "3.10"]
      # Don't cancel all jobs if one fails
      fail-fast: false

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}  # Ensure we get the latest linted code
        fetch-depth: 0
    
    - name: Wait for lint changes
      run: |
        sleep 10  # Give time for any lint commits to be pushed
        git pull origin ${{ github.head_ref || 'main' }} --rebase
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pyqt5 \
          qtbase5-dev \
          qt5-qmake \
          qttools5-dev-tools \
          xvfb
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        # Install test dependencies first to avoid conflicts
        pip install pytest pytest-cov pytest-mock pytest-qt
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        pip install PyQt5-stubs no-implicit-optional
        
    - name: Check for implicit optionals
      run: |
        no_implicit_optional jellyfin_music_organizer
        
    - name: Run tests with pytest
      env:
        QT_QPA_PLATFORM: offscreen
        DISPLAY: ":99.0"
      run: |
        # Start Xvfb
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        # Run tests with verbose output
        pytest tests/ -v --cov=jellyfin_music_organizer --cov-report=xml
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: true 
