name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        # Try different package names for PyQt5
        sudo apt-get install -y \
          python3-pyqt5 \
          qtbase5-dev \
          qt5-qmake \
          qttools5-dev-tools \
          xvfb
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        
    - name: Run tests with pytest
      env:
        QT_QPA_PLATFORM: offscreen
        DISPLAY: ":99.0"
      run: |
        # Start Xvfb
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        # Run tests
        pytest tests/ --cov=jellyfin_music_organizer --cov-report=xml
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml 
